apiVersion: v1
kind: Template
labels:
  app: ${APP_NAME}
metadata:
  name: ${APP_NAME}
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}-route
    labels:
      app: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}-svc

- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-svc
    namespace: default
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
    selector:
      app: ${APP_NAME}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}-dep
    labels:
      app: ${APP_NAME}
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          imagePullPolicy: Always
          image: ${IMAGE_URL}
          ports:
          - containerPort: 5000
            name: plaintext-port
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 500Mi
          env:
          - name: MODEL_ARTIFACT_URI
            value: ${MODEL_ARTIFACT_URI}
          - name: AWS_ACCESS_KEY_ID
            value: ${AWS_ACCESS_KEY_ID}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${AWS_SECRET_ACCESS_KEY}

parameters:
- name: IMAGE_URL
  description: URL of the docker image
- name: APP_NAME
  description: Application to use in OpenShift
  value: mlflow-serve-api
- name: MODEL_ARTIFACT_URI
  description: Path of Model Artifact. If the tracking server is intended for other people to access remotely, file store is not recommended.
  value: "s3://bucket/artifacts"
- name: AWS_ACCESS_KEY_ID
  description: AWS Access Key ID which has access to S3 bucket mentioned above.
- name: AWS_SECRET_ACCESS_KEY
  description: AWS Access Key Secret which has access to S3 bucket mentioned above.